site_name: Sam's Website
site_url: https://flamerten.github.io/portfolio/
repo_url: https://github.com/flamerten # direct users to my github page
edit_uri: "" # Hides the "Edit this page" button

theme:
  name: material
  palette:
      - scheme: default
        primary: blue-grey
        accent: red
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - scheme: slate
        primary: blue-grey
        accent: deep-orange
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
  features:
    - navigation.tabs   
    - navigation.top    
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - navigation.footer
    - navigation.expand
    - content.code.copy
    - content.code.annotate
    - toc.follow
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/chip # Microchip font
    repo: fontawesome/brands/github


markdown_extensions:
  - attr_list                # For styling images/buttons
  - admonition               # Obsidian Callouts
  - pymdownx.details         # Collapsible sections
  - pymdownx.highlight:      # Enhanceda Code Highlighting
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.magiclink
  - pymdownx.tabbed:        # Tabbed blocks code
      alternate_style: true
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

# Your plugins
plugins:
  - search                   # Standard search bar
  - awesome-nav
  - macros
  - tags:
      tags_hierarchy: true
  - blog
  - pub-obsidian:
      obsidian_dir: .obsidian
      backlinks:
        enabled: false
      callouts:
        enabled: true
        indentation: spaces
      comments:
        enabled: true
        inject_as_html: false
      links:
        wikilinks_enabled: true
  - git-revision-date-localized:
      type: timeago
  - mermaid2
  - glightbox:
      touchNavigation: true
      loop: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/flamerten
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/samuelyow/

extra_css:
  - stylesheets/extra.css
  - stylesheets/project.css
  - stylesheets/misc.css