site_name: My Portfolio
site_url: https://flamerten.github.io/portfolio/
repo_url: https://github.com/flamerten # direct users to my github page
edit_uri: "" # Hides the "Edit this page" button

theme:
  name: material
  palette: 
      - scheme: default
        primary: navy
        accent: purple 
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - scheme: slate
        primary: navy
        accent: lime
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
  features:
    - navigation.tabs   
    - navigation.top    
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - navigation.footer
    - content.code.copy
    - content.code.annotate
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/chip # Microchip font
    repo: fontawesome/brands/github

# Extensions to make your notes look professional
markdown_extensions:
  - attr_list                # For styling images/buttons
  - admonition               # Obsidian Callouts
  - pymdownx.details         # Collapsible sections
  - pymdownx.superfences     # Nesting codeblocks
  - pymdownx.highlight:      # Enhanceda Code Highlighting
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.magiclink
  - pymdownx.tabbed:        # Tabbed blocks code
      alternate_style: true

# Your plugins
plugins:
  - search                   # Standard search bar
  - tags:
      tags_file: tags.md
  - pub-obsidian:
      obsidian_dir: .obsidian
      backlinks:
        enabled: false
      callouts:
        enabled: true
        indentation: spaces
      comments:
        enabled: true
        inject_as_html: false
      links:
        wikilinks_enabled: true
  - git-revision-date-localized:
      type: timeago
  - mermaid2
  - glightbox:
      touchNavigation: true
      loop: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/flamerten
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/samuelyow/

# MathJax javascript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js